# Generated by Django 4.0.8 on 2022-10-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0002_newuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trains',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trains',
            name='origin',
        ),
    ]
