# Generated by Django 4.0.8 on 2022-10-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0003_remove_trains_destination_remove_trains_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='ac',
            field=models.PositiveSmallIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='trains',
            name='sl',
            field=models.PositiveSmallIntegerField(default=800),
        ),
        migrations.AddField(
            model_name='trains',
            name='train_no',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
