# Generated by Django 4.0.8 on 2022-10-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0004_trains_ac_trains_sl_trains_train_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.TimeField()),
                ('station_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.stations')),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.trains')),
            ],
        ),
    ]
