# Generated by Django 4.0.8 on 2022-11-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0005_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='station_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stn', to='railways.stations'),
        ),
        migrations.AlterField(
            model_name='trains',
            name='ac',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='trains',
            name='sl',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='TrainDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_days', models.ManyToManyField(to='railways.days')),
                ('trains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.trains')),
            ],
        ),
    ]
