# Generated by Django 4.0.8 on 2022-11-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0006_days_alter_timetable_station_code_alter_trains_ac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('train', models.IntegerField()),
            ],
        ),
    ]
