# Generated by Django 4.0.8 on 2022-11-01 16:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0007_psg'),
    ]

    operations = [
        migrations.AddField(
            model_name='psg',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psg',
            name='doj',
            field=models.DateField(default=datetime.date(2022, 11, 1)),
            preserve_default=False,
        ),
    ]
