# Generated by Django 4.0.8 on 2022-11-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0008_psg_created_psg_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psg',
            name='doj',
            field=models.CharField(max_length=50),
        ),
    ]
