# Generated by Django 4.0.8 on 2022-11-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0012_seats_remove_trains_ac_remove_trains_sl_psg_coach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='train',
        ),
        migrations.AddField(
            model_name='seats',
            name='train_no',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='railways.trains'),
            preserve_default=False,
        ),
    ]
