# Generated by Django 4.0.8 on 2022-11-04 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0013_remove_seats_train_seats_train_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='type',
            field=models.CharField(default='E', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('st_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.stations')),
                ('st_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_st', to='railways.stations')),
            ],
        ),
    ]
