# Generated by Django 4.0.8 on 2022-11-06 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0016_alter_trains_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
